# Generated by Django 4.2.6 on 2024-03-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.worker')),
                ('subordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_subordinates', to='attendance.worker')),
            ],
            bases=('attendance.worker',),
        ),
    ]
