# Generated by Django 4.2.6 on 2024-03-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_customuser_is_manager_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='subordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_subordinates', to='attendance.worker'),
        ),
    ]
