# Generated by Django 4.2.6 on 2024-03-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_manager_subordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='subordinates',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='worker_ptr',
        ),
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='firstname',
            field=models.TextField(blank=True, max_length=500, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='kiosk_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='kiosk_code'),
        ),
        migrations.AddField(
            model_name='manager',
            name='lastname',
            field=models.TextField(blank=True, max_length=255, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workers', to='attendance.manager'),
        ),
    ]
