# Generated by Django 4.2.6 on 2023-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='lastname',
            field=models.TextField(blank=True, max_length=255, verbose_name='lastname'),
        ),
    ]
