# Generated by Django 3.2.12 on 2024-05-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_worktime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
